FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY ./requirements/app/ .
COPY ./requirements/migrate/tools/migrations ./migrations
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o app ./cmd
CMD ["/app/app"]
# FROM scratch
# COPY --from=builder /app/app /app/app
# COPY --from=builder /app/migrations /app/migrations
# WORKDIR /app
# CMD ["/app/app"]